### ISSUE TITLE
setup_gdi.sql: SET ROLE :PG_USER darf nicht mehr drinstehen

### ISSUE THREAD

**Issue by schmandr** [sogis-oereb/oereb-db#2]
### Beschreibung

In _setup_gdi.sql_ darf die erste Zeile `SET ROLE :PG_USER;` nicht mehr vorkommen, weil das Skript nun ja nicht mehr durch einen DB-Admin manuell (mit _psql_), sondern durch einen Schema-Job ausgeführt wird.

**Comment by edigonzales** [comment]
fixed
